### ISSUE TITLE
US1 - Car List

### ISSUE THREAD

**Issue by TienPham18** [TienPham18/AutoWelt-Repo#2]
## Value proposition

`As a` car buyer
`I want to` see a list of available cars
`In order to` have an overview of all services currently provided by the hotel

## Description

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139952562/5c6cd6c9-458e-4898-a749-7bae59c842d0)

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139952562/008d0438-6d45-4fad-96d2-d8723d0a18d8)

## Acceptance criteria

- [ ] On the homepage, you can see the following:
    - [ ] the name of the hotel: "Hotel Tishjama"
    - [ ] the word "Services"
    - [ ] a list of services, including the name of the service and an image
- [ ] In the event of an error, you can see an error message.

## Tasks

- [ ] create feature branch: feature/service-list
- [ ] on mongo.db, create a database called "Tishjama" and a collection called "services
  - [ ] enter the preexisting list of services into the collection
- [ ] fetch a list of services from the API
  - [ ] implement the error handling logic to display an error message if there is an issue loading data from the API
- [ ] map through the fetched list of services

- [ ] in _app.js:
  - [ ] render an `<h1>` element for the hotel/app name

- [ ] in the index.js:
  - [ ] render an `<h2>` element for the word "Services"
  - [ ] render an unordered list which contains all services and shows for each service: 
    - [ ] the name of the service
    - [ ] an image
    

```
