### ISSUE TITLE
US2 - Details of a Car

### ISSUE THREAD

**Issue by TienPham18** [TienPham18/AutoWelt-Repo#3]
## Value proposition

`As a` car buyer
`I want to` see the details of the car I am interested in 
`In order to` check whether the details of the selected car is suitable for a buy

## Acceptance criteria

- [ ] 

## Tasks

- [ ] create a feature branch: feature/detail-page
- [ ] create "components/ServiceCard/index.js"  
  - [ ] in the return statement render the following: 
    - [ ] an `<h2>` element "Service"
    - [ ] an `<article>` which contains the following information:
      - [ ] service image
      - [ ] service name
      - [ ] description
      - [ ] date
      - [ ] time
      - [ ] price with currency (€)
    - [ ] a link back to the service list page which contains the text "<- back"

- [ ] create "pages/api/services/index.js" 
  - [ ] fetch all services
- [ ] create "pages/api/services/[id].js"
  - [ ] fetch one service by id
- [ ] create a link from service list items to the "ServiceCard" by id

### Files struture 

```
