### ISSUE TITLE
US3 - Add a Service

### ISSUE THREAD

**Issue by TienPham18** [TienPham18/AutoWelt-Repo#4]
## Value proposition

As a hotel service manager
I want to add a service
In order to offer our guests even more services

## Description

![Image](https://user-images.githubusercontent.com/139991612/268308734-142d90ec-3ed4-4f63-bc57-c12390099b84.png)

## Acceptance criteria

- [ ] on the service list, there is a button to add a new service
- [ ] when the "Add Service" button is clicked, the user should be directed to a new page with a form to add the service details
- [ ] on the form page, the user can see the following:
  - [ ] the hotel name "Hotel Tishjama"
  - [ ] the words "Add service"
  - [ ] a form which contains the fields:
    - [ ] a text field: "service name"
    - [ ] a text field: "image"
    - [ ] a text area: "description"
    - [ ] a date picker: "date" 
    - [ ] a time picker: "time"
    - [ ] a number field with currency (€): "price"
    - [ ] a "cancel" button which directs the user back to the service list page
    - [ ] an "add service" button--if the form is successfully submitted, the user should be directed back to the service list page where the new service is displayed
      - [ ] the user receives a confirmation prompt or message when the form is successfully submitted
      - [ ] if the user tries to submit an empty form, an error message is displayed indicating which fields are mandatory (all fields are mandatory)

## Tasks

- [ ] create a branch: feature/add-service
- [ ] create "components/ServiceForm/index.js"
- [ ] create an `<h2>` element: "Add Service"
- [ ] create a form with the following fields:
  - [ ] service name
  - [ ] image 
  - [ ] description
  - [ ] date
  - [ ] time
  - [ ] price
    - [ ] (all fields are required) 
  - [ ] create a "cancel" button that links back to the service list page without saving 
  - [ ] create an "add" button that shows a confirmation prompt with the text "New service successfully added" and an "ok" button that links back to the service list page
- [ ] in the service list page, create a link with the text "+ add service" which links to the "ServiceForm" component

```
